# Configurations
title:            酒馆小助手
longtitle:        Fishy的酒馆小助手

remote_theme:     sighingnow/jekyll-gitbook

# Copyright
author: Fishy
copyright_year: 2025
copyright_name: Fishy

toc:
    enabled: true
    h_min: 1
    h_max: 3

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
  tools:
    output: true
    permalink: /:collection/:path/

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
