# Configurations
title:            ğŸŸSilly Wiki
longtitle:        Fishyçš„é…’é¦†å°åŠ©æ‰‹

remote_theme:     sighingnow/jekyll-gitbook

toc:
    enabled: true
    h_min: 1
    h_max: 3

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
  tools:
    output: true
    permalink: /:collection/:path/
  css:
    output: true
    permalink: /:collection/:path/

favicon_path:  Fish.svg

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
